# TCL File Generated by Component Editor 18.1
# Fri Jan 11 17:11:57 CET 2019
# DO NOT MODIFY


# 
# histeq_calc "histeq_calc" v1.0
# Dejan Lukic 2019.01.11.17:11:57
# histogram calculation accelerator
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module histeq_calc
# 
set_module_property DESCRIPTION "histogram calculation accelerator"
set_module_property NAME histeq_calc
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Dejan Lukic"
set_module_property DISPLAY_NAME histeq_calc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL acc_linear_function
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file histeq_calc_accel.vhd VHDL PATH histeq_calc_accel.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point params
# 
add_interface params avalon end
set_interface_property params addressUnits WORDS
set_interface_property params associatedClock clock
set_interface_property params associatedReset reset
set_interface_property params bitsPerSymbol 8
set_interface_property params burstOnBurstBoundariesOnly false
set_interface_property params burstcountUnits WORDS
set_interface_property params explicitAddressSpan 0
set_interface_property params holdTime 0
set_interface_property params linewrapBursts false
set_interface_property params maximumPendingReadTransactions 0
set_interface_property params maximumPendingWriteTransactions 0
set_interface_property params readLatency 0
set_interface_property params readWaitTime 1
set_interface_property params setupTime 0
set_interface_property params timingUnits Cycles
set_interface_property params writeWaitTime 0
set_interface_property params ENABLED true
set_interface_property params EXPORT_OF ""
set_interface_property params PORT_NAME_MAP ""
set_interface_property params CMSIS_SVD_VARIABLES ""
set_interface_property params SVD_ADDRESS_GROUP ""

add_interface_port params avs_params_address address Input 1
add_interface_port params avs_params_read read Input 1
add_interface_port params avs_params_readdata readdata Output 32
add_interface_port params avs_params_write write Input 1
add_interface_port params avs_params_writedata writedata Input 32
add_interface_port params avs_params_waitrequest waitrequest Output 1
set_interface_assignment params embeddedsw.configuration.isFlash 0
set_interface_assignment params embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment params embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment params embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point in
# 
add_interface in avalon_streaming end
set_interface_property in associatedClock clock
set_interface_property in associatedReset reset
set_interface_property in dataBitsPerSymbol 8
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits true
set_interface_property in maxChannel 0
set_interface_property in readyLatency 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in asi_in_data data Input 8
add_interface_port in asi_in_ready ready Output 1
add_interface_port in asi_in_valid valid Input 1
add_interface_port in asi_in_eop endofpacket Input 1
add_interface_port in asi_in_sop startofpacket Input 1


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clock
set_interface_property out associatedReset reset
set_interface_property out dataBitsPerSymbol 8
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out aso_out_data data Output 32
add_interface_port out aso_out_ready ready Input 1
add_interface_port out aso_out_valid valid Output 1
add_interface_port out aso_out_empty empty Output 1
add_interface_port out aso_out_eop endofpacket Output 1
add_interface_port out aso_out_sop startofpacket Output 1

